-- DDL(DATA DEFINITION LANGUAGE)
-- CREATE,ALTER(ADD, DROP, RENAME, MODIFY COLUMN), DROP TABLE,TRUNCATE
-- CREATE DATABASE
CREATE DATABASE COLLEGE;

USE COLLEGE;

-- CREATE TABLE
CREATE TABLE STUDENTS(
ROLL_ID INT UNSIGNED PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
AGE INT UNSIGNED,
GENDER VARCHAR(1),
MOB_NO VARCHAR(16));

CREATE TABLE DEPARTMENTS(
DEPT_ID INT UNSIGNED PRIMARY KEY,
DEPT_NAME VARCHAR(30) NOT NULL,
HOD VARCHAR(25));

CREATE TABLE OFFICE_INFO(
OFFICE_ID INT UNSIGNED PRIMARY KEY,
NAME VARCHAR(20) NOT NULL,
HOF VARCHAR(20));

CREATE TABLE STAFF(
STAFF_ID INT UNSIGNED PRIMARY KEY,
MEMBER_NAME VARCHAR(25) NOT NULL);

CREATE TABLE NON_TEACHING_STAFF(
ID INT UNSIGNED PRIMARY KEY,
NAME VARCHAR(30),
AGE INT UNSIGNED);

-- ALTER (ADD COLUMN)
ALTER TABLE STAFF ADD COLUMN AGE INT UNSIGNED;
SELECT * FROM STAFF;

-- ALTER (DROP COLUMN)
ALTER TABLE OFFICE_INFO DROP COLUMN NAME;
SELECT * FROM OFFICE_INFO;

-- ALTER (RENAME COLUMN)
ALTER TABLE STUDENTS RENAME COLUMN NAME TO  STUDENT_NAME;
SELECT * FROM STUDENTS;

-- ALTER (MODIFY COLUMN)(CHANGING DTATYPE)
ALTER TABLE STUDENTS MODIFY COLUMN MOB_NO VARCHAR(20);
-- DESC/DESCRIBE(TO SEE DATATYPE INFO)
DESC STUDENTS;

-- DROP TABLE
DROP TABLE NON_TEACHING_STAFF;

SELECT * FROM STAFF;
INSERT INTO STAFF 
VALUES(1, 'KRISHNA',45),
(2,'RADHA',35);
-- TRUNCATE(DELITING ALL RECORDS FROM TABLE, STRUCTURE REAMINS AS IT IS)
TRUNCATE STAFF;
-- WE CAN'T USE WHERE CLAUSE IN TRUNCATE
TRUNCATE STAFF; 

